### ISSUE TITLE
Calloc not defined

### ISSUE THREAD

**Issue by GameMakerJake** [halildurmus/win32#148]
I'm trying to test the code in the examples and hit an issue I can not resolve. It seems `calloc` isn't defined.

Dart version: `Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "windows_x64"`

Here's the example code I'm copying from, Literally copy and pasting: https://github.com/timsneath/win32/blob/master/example/hello.dart

The error I'm getting is:

```
C:\tools\dart-sdk\bin\dart.exe --enable-asserts C:\Users\Mewtwo\IdeaProjects\BuilderProX\bin\BuilderProX.dart
bin/BuilderProX.dart:21:18: Error: Method not found: 'calloc'.
      final ps = calloc<PAINTSTRUCT>();
                 ^^^^^^
bin/BuilderProX.dart:23:20: Error: Method not found: 'calloc'.
      final rect = calloc<RECT>();
                   ^^^^^^
bin/BuilderProX.dart:43:14: Error: Method not found: 'calloc'.
  final wc = calloc<WNDCLASS>()
             ^^^^^^
bin/BuilderProX.dart:81:15: Error: Method not found: 'calloc'.
  final msg = calloc<MSG>();
              ^^^^^^
```

Spec:

```
name: BuilderProX
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  win32: ^1.7.4
```

pub get:
```
C:\Users\Mewtwo\IdeaProjects\BuilderProX>pub get
Resolving dependencies...
+ ffi 0.1.3
+ meta 1.2.4
+ pedantic 1.9.2
+ win32 1.7.4
Changed 4 dependencies!
```

Any ideas what I'm doing wrong?
