### ISSUE TITLE
CreateEvent Function

### ISSUE THREAD

**Issue by FengChendian** [halildurmus/win32#282]
Hi! Does this package support CreateEvent Function? 

I try to implement some function like [Monitoring Communications Events](https://docs.microsoft.com/en-us/windows/win32/devio/monitoring-communications-events). But I can't find **CreateEvent** Funtion in win32 package.

Here is CreateEvent doc:
https://docs.microsoft.com/en-us/windows/win32/devio/monitoring-communications-events

**Comment by ilopX** [comment]
As a temporary solution, I suggest using this fork.

```yaml
dependencies:
  win32:
    git:
      url: https://github.com/ilopX/win32
      ref: create_event
```
