### ISSUE TITLE
Pointer.fromFunction<WindowProc>( handleWindowMessages, 0);  is unable to convert

### ISSUE THREAD

**Issue by famlar** [halildurmus/win32#685]
- The error location is in ` final lpfnNewWndProc = Pointer.fromFunction<WindowProc>(handleWindowMessages, 0); `
- The error message is `The type 'IntPtr Function(IntPtr, Uint32, IntPtr, IntPtr)' must be a subtype of 'IntPtr Function(IntPtr, Uint32,IntPtr, IntPtr)' for 'fromFunction'.Try changing one or both of the type arguments.

```dart
import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:flutter/foundation.dart';
import 'package:win32/win32.dart';

// 定义新的窗口过程函数
LRESULT handleWindowMessages(
    HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam) {
  switch (uMsg as int) {
    case WM_NCLBUTTONDOWN:
      // 处理鼠标左键按下事件
      if (kDebugMode) {
        print("NCLBUTTON DOWN");
      }
      break;
    default:
      // 调用原始窗口过程函数
      return CallWindowProc(
          GetWindowLongPtr(hWnd as int, GWLP_WNDPROC) as Pointer<
              NativeFunction<IntPtr Function(IntPtr, Uint32, IntPtr, IntPtr)>>,
          hWnd as int,
          uMsg as int,
          wParam as int,
          lParam as int) as LRESULT;
  }
  return 0 as LRESULT;
}

void setHook({bool hook=true}) {
  // 获取本窗口句柄
  final hWnd = GetActiveWindow();

  // 获取原始窗口过程函数地址
  final lpfnOldWndProc = GetWindowLongPtr(hWnd, GWLP_WNDPROC);

  // 定义新的窗口过程函数并创建一个 Pointer 类型的对象
  final lpfnNewWndProc = Pointer.fromFunction<WindowProc>(
      handleWindowMessages, 0);

  // 使用 SetWindowLongPtr 函数将新的窗口过程函数地址设置为窗口的过程函数
  SetWindowLongPtr(hWnd, GWLP_WNDPROC, lpfnNewWndProc.address);

  // 使用 SetWindowLongPtr 函数恢复原始窗口过程函数
  if (!hook) {
    SetWindowLongPtr(hWnd, GWLP_WNDPROC, lpfnOldWndProc);
  }
}

```

pubspec.yaml

```yaml
name: flutter_notepad
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  win32: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
